import { Command } from 'commander';
import { writeFileSync } from 'fs';
import chalk from 'chalk';
import { getAPIClientFromOptions, getGlobalOptions, withErrorHandling } from '../../lib/utils/api-helper.js';

export const generateCommand = new Command('generate')
  .alias('gen')
  .description('Code generation commands');

const typesCommand = new Command('types')
  .description('Generate TypeScript types from ABSmartly configuration')
  .option('-o, --output <path>', 'output file path')
  .option('--app <name>', 'application to generate types for')
  .action(withErrorHandling(async (options) => {
    const globalOptions = getGlobalOptions(typesCommand);
    const client = await getAPIClientFromOptions(globalOptions);

    const allExperiments = [];
    const itemsPerPage = 100;
    let page = 1;
    let hasMore = true;

    while (hasMore) {
      const batch = await client.listExperiments({ items: itemsPerPage, page });
      if (!Array.isArray(batch)) break;
      allExperiments.push(...batch);
      if (batch.length < itemsPerPage) hasMore = false;
      else page++;
    }

    console.log(chalk.gray(`Fetched ${allExperiments.length} experiments from ${page} pages`));

    const experiments = allExperiments as Array<Record<string, unknown>>;
    const uniqueNames = [...new Set(experiments.map(e => e.name as string).filter(Boolean))].sort();

    const variantsByExp = new Map<string, string[]>();
    for (const exp of experiments) {
      const name = exp.name as string;
      if (!name) continue;
      const variants = exp.variants as Array<Record<string, unknown>> | undefined;
      if (variants && !variantsByExp.has(name)) {
        variantsByExp.set(name, variants.map(v => v.name as string).filter(Boolean));
      }
    }

    const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

    const experimentEntries = uniqueNames.map(name => {
      const variants = variantsByExp.get(name) ?? [];
      const variantType = variants.length > 0
        ? variants.map(v => `'${escape(v)}'`).join(' | ')
        : 'string';
      return `  '${escape(name)}': { variants: ${variantType} }`;
    });

    const typesContent = `// Generated by ABSmartly CLI
// ${new Date().toISOString()}
// ${uniqueNames.length} experiments

/**
 * Map of all experiment names to their variant configurations.
 * Use with the ABSmartly SDK for type-safe experiment access.
 */
export interface ABSmartlyExperiments {
${experimentEntries.join(';\n')};
}

/** All known experiment names */
export type ExperimentName = keyof ABSmartlyExperiments;

/**
 * Type-safe wrapper for ABSmartly SDK context.
 *
 * Usage:
 *   const variant = context.treatment('my_experiment'); // returns number (0, 1, 2...)
 *   const value = context.variableValue('my_variable', defaultValue);
 */
export interface TypedABSmartlyContext {
  treatment(experimentName: ExperimentName): number;
  variableValue<T>(key: string, defaultValue: T): T;
  peekTreatment(experimentName: ExperimentName): number;
  peekVariableValue<T>(key: string, defaultValue: T): T;
}
`;

    if (options.output) {
      writeFileSync(options.output, typesContent, 'utf8');
      console.log(chalk.green(`Types written to ${options.output}`));
    } else {
      console.log(typesContent);
    }
  }));

generateCommand.addCommand(typesCommand);
