import { Command } from 'commander';
import { writeFileSync } from 'fs';
import chalk from 'chalk';
import { getAPIClientFromOptions, getGlobalOptions, withErrorHandling } from '../../lib/utils/api-helper.js';

export const generateCommand = new Command('generate')
  .alias('gen')
  .description('Code generation commands');

const typesCommand = new Command('types')
  .description('Generate TypeScript types from ABSmartly configuration')
  .option('-o, --output <path>', 'output file path')
  .option('--app <name>', 'application to generate types for')
  .action(withErrorHandling(async (options) => {
    const globalOptions = getGlobalOptions(typesCommand);
    const client = await getAPIClientFromOptions(globalOptions);

    // Fetch all experiments using pagination
    const allExperiments = [];
    const limit = 100;
    let offset = 0;
    let hasMore = true;

    while (hasMore) {
      const batch = await client.listExperiments({ limit, offset });
      allExperiments.push(...batch);

      if (batch.length < limit) {
        hasMore = false;
      } else {
        offset += limit;
      }
    }

    if (process.env.DEBUG) {
      console.error(chalk.gray(`Fetched ${allExperiments.length} experiments`));
    }

    const uniqueNames = [...new Set(allExperiments.map((e) => e.name).filter(Boolean))];

    const typesContent = `// Generated by ABSmartly CLI
// Generated at: ${new Date().toISOString()}

export type ExperimentName =
${uniqueNames.map((name) => `  | '${name}'`).join('\n')};

export type VariantName = 'control' | 'treatment';

export interface ExperimentContext {
  treatment(experimentName: ExperimentName): VariantName;
  variable<T>(experimentName: ExperimentName, defaultValue: T): T;
}
`;

    if (options.output) {
      writeFileSync(options.output, typesContent, 'utf8');
      console.log(chalk.green(`✓ Types written to ${options.output}`));
    } else {
      console.log(typesContent);
    }
  }));

generateCommand.addCommand(typesCommand);
